#!/usr/bin/env python3
"""
Weekly Podcast Investor Digest
Fetches RSS feeds, summarizes episodes with Claude, emails via Gmail SMTP.
"""

import os
import smtplib
import argparse
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import config
from scrapers.podcast_rss import fetch_all_podcasts
from summarizer import summarize_all


# ── Email builder ──────────────────────────────────────────────────────────────

def build_html(summaries: list[dict], week_of: str) -> str:
    rows = ""
    for ep in summaries:
        pub = ep["published"][:10]
        rows += f"""
        <div style="margin-bottom:32px;border-left:4px solid #1a73e8;padding-left:16px;">
          <p style="margin:0 0 2px;font-size:12px;color:#888;">{ep['podcast']} &middot; {pub}</p>
          <h2 style="margin:0 0 8px;font-size:16px;">
            <a href="{ep['url']}" style="color:#1a73e8;text-decoration:none;">{ep['title']}</a>
          </h2>
          <div style="font-size:14px;line-height:1.6;white-space:pre-wrap;">{ep['investor_summary']}</div>
        </div>"""

    return f"""<!DOCTYPE html>
<html>
<body style="font-family:Arial,sans-serif;max-width:680px;margin:auto;padding:24px;color:#222;">
  <h1 style="font-size:22px;border-bottom:2px solid #1a73e8;padding-bottom:8px;">
    Podcast Investor Digest &mdash; Week of {week_of}
  </h1>
  <p style="color:#555;font-size:13px;">
    {len(summaries)} episode(s) summarized through an investor lens.
  </p>
  {rows}
  <hr style="margin-top:40px;border:none;border-top:1px solid #eee;">
  <p style="font-size:11px;color:#aaa;text-align:center;">
    Generated by tmt-news podcast digest &middot; powered by Claude
  </p>
</body>
</html>"""


def build_plain(summaries: list[dict], week_of: str) -> str:
    lines = [
        f"PODCAST INVESTOR DIGEST — Week of {week_of}",
        "=" * 60,
        f"{len(summaries)} episode(s) summarized.",
        "",
    ]
    for ep in summaries:
        pub = ep["published"][:10]
        lines += [
            f"{ep['podcast']} | {pub}",
            ep["title"],
            ep["url"],
            "",
            ep["investor_summary"],
            "",
            "-" * 60,
            "",
        ]
    return "\n".join(lines)


# ── Gmail SMTP sender ──────────────────────────────────────────────────────────

def send_gmail(subject: str, html_body: str, plain_body: str):
    gmail_user = os.environ["GMAIL_USERNAME"]
    gmail_pass = os.environ["GMAIL_APP_PASSWORD"]
    to_addr = os.environ.get("DIGEST_TO_EMAIL", gmail_user)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = gmail_user
    msg["To"] = to_addr
    msg.attach(MIMEText(plain_body, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.ehlo()
        server.starttls()
        server.login(gmail_user, gmail_pass)
        server.sendmail(gmail_user, to_addr, msg.as_string())
    print(f"Email sent to {to_addr}")


# ── Main ───────────────────────────────────────────────────────────────────────

def run(days: int = 7, dry_run: bool = False):
    week_of = datetime.now().strftime("%B %d, %Y")
    print(f"\nPodcast Investor Digest — {week_of}")
    print(f"Fetching episodes from the last {days} days...")

    episodes = fetch_all_podcasts(config.PODCASTS, days=days)
    if not episodes:
        print("No new episodes found. Exiting.")
        return

    print(f"\nSummarizing {len(episodes)} episode(s) with Claude...")
    summaries = summarize_all([ep.to_dict() for ep in episodes])

    html = build_html(summaries, week_of)
    plain = build_plain(summaries, week_of)

    if dry_run:
        out = f"output/podcast_digest_{datetime.now().strftime('%Y-%m-%d')}.html"
        import os; os.makedirs("output", exist_ok=True)
        with open(out, "w") as f:
            f.write(html)
        print(f"Dry run — saved to {out}")
    else:
        subject = f"Podcast Investor Digest — {week_of}"
        send_gmail(subject, html, plain)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Weekly Podcast Investor Digest")
    parser.add_argument("--days", type=int, default=7, help="Look back N days (default 7)")
    parser.add_argument("--dry-run", action="store_true", help="Save HTML locally instead of emailing")
    args = parser.parse_args()
    run(days=args.days, dry_run=args.dry_run)
